baseURL: "https://simeonhorner.com/"
languageCode: "en-gb"
title: "Simeon's Site"
theme: "hugo-bearblog"

menu:
  main:
    - identifier: home
      name: Home
      url: "/"
      weight: 1

    - identifier: posts
      name: Posts
      url: "/posts/"
      weight: 2

    - identifier: quotes
      name: Quotes
      url: "/quotes/"
      weight: 3



outputs:
  home: ["HTML"]
  section: ["HTML"]
  page: ["HTML"]
